name: BankAccounts
version: '${project.version}'
main: pro.cloudnode.smp.bankaccounts.BankAccounts
api-version: "1.20"
author: Cloudnode
softdepend:
    - PlaceholderAPI
    - Vault
libraries:
    - org.mariadb.jdbc:mariadb-java-client:3.5.7
    - com.zaxxer:HikariCP:7.0.2
commands:
    bank:
        description: Bank Accounts
        usage: /<command> help
    pos:
        description: Create point of sale
        usage: /<command>
    baltop:
        description: Balance leaderboard
        usage: /<command>
    invoice:
        description: Invoicing and payment requests
        usage: /<command>
