name: BankAccounts
version: '${project.version}'
main: pro.cloudnode.smp.bankaccounts.BankAccounts
api-version: "1.20"
author: Cloudnode
softdepend:
    - PlaceholderAPI
commands:
    bank:
        description: Bank Accounts
        usage: /<command> help
    pos:
        description: Create point of sale
        usage: /<command>
