name: Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Set version from release tag
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build and package Maven project
        run: mvn -B clean package --file pom.xml

      - name: Upload to release
        uses: cloudnode-pro/release-upload-asset@1.0.2
        with:
          gh-token: ${{ github.token }}
          files: target/BankAccounts-${{ github.event.release.tag_name }}.jar; type=application/java-archive

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ github.event.repository.custom_properties.modrinth_id }}
          name: ${{ github.event.release.name == github.event.release.tag_name && format('BankAccounts {0}', github.event.release.name) || github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: paper
          dependencies: |-
            [{
              "project_id": "lKEzGugV",
              "dependency_type": "optional"
            }]
          game-versions: |-
            1.20.x
            1.21.x
          files: target/BankAccounts-${{ github.event.release.tag_name }}.jar
